<?php
/**
 * Created by PhpStorm.
 * User: Aziz Juraev
 * Date: 29.08.2019
 * Time: 13:05
 */

namespace app\widgets;


use app\models\Employees;
use Yii;
use yii\bootstrap\Nav;

class EmployeeMenu extends Nav
{

    /**
     * @var Employees
     */
    public $model;

    public $encodeLabels = false;

    public function init()
    {
        $this->items = [
            [
                'label' => '<span class="glyphicon glyphicon-user"></span> '.Yii::t('app','Info'),
                'url' => ['/employee/view','id'=>$this->model->id]
            ],
            [
                'label' => '<span class="glyphicon glyphicon-edit"></span> '.Yii::t('app','Update main data'),
                'url' => ['/employee/update','id'=>$this->model->id]
            ],
            [
                'label' => '<span class="glyphicon glyphicon-education"></span> '.Yii::t('app','Update education data'),
                'url' => ['/employee/update-education','id'=>$this->model->id]
            ],
            [
                'label' => '<span class="glyphicon glyphicon-briefcase"></span> '.Yii::t('app','Update exerience data'),
                'url' => ['/employee/update-experience','id'=>$this->model->id]
            ],
            [
                'label' => '<span class="glyphicon glyphicon-file"></span> PDF',
                'url' => ['/employee/pdf','id'=>$this->model->id],
                'linkOptions' => ['target'=>'_blank'],
            ],
            [
                'label' => '<span class="glyphicon glyphicon-trash"></span> '.Yii::t('app','Delete'),
                'linkOptions' => [
                    'class' => 'danger',
                    'data' => [
                        'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                        'method' => 'post',
                    ],
                ],
                'url' => ['/employee/delete','id'=>$this->model->id]
            ],
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

}